version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    ports: 
      # Port for neo4j web DB inspection tool
      - 7474:7474 
      # Actual database port
      - 7687:7687
    volumes:
      - neo4j_db:/data/
    env_file:
      - ./packages/server/.env

volumes:
  neo4j_db:
    name: diploma_db
